import house from 'assets/houses/free-photo-of-bezienswaardigheid-attractie-toren-monument.jpeg';
import house2 from 'assets/houses/heemstede_glipperdreef_209_bosbeek_hoofdgebouw.jpg';
import house3 from 'assets/houses/herengracht_gereed_6_20210120013744-480x640.jpg';

export const products = [
  {
    image: house,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house2,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house3,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house2,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house3,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house2,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house3,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house2,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house3,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house2,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house3,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house2,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
  {
    image: house3,
    title: 'fhfgh',
    date: 'fghfgh',
    workPerformed: 'fghfgh',
    address: 'fghfhgfh',
    description: ['ghghghgh', 'fghfgh'],
  },
];
